services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    networks:
      - cloudflare
    environment:
      MYSQL_PASSWORD: examplepassword
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_USER: nextcloud
      MYSQL_HOST: db
    volumes:
      - nextcloud_data:/var/www/html
    ports:
      - "8080:80"  # Adjust to your desired port

  db:
    image: mariadb:latest
    container_name: nextcloud_db
    restart: unless-stopped
    networks:
      - cloudflare
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_PASSWORD: examplepassword
      MYSQL_USER: nextcloud
      MYSQL_DATABASE: nextcl