services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    networks:
      - cloudflare
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_HOST: db
    volumes:
      - /home/weissi/docker/nextcloud:/var/www/html
    ports:
      - "8080:80"  # Adjust to your desired port

  db:
    image: mariadb:latest
    container_name: nextcloud_db
    restart: unless-stopped
    networks:
      - cloudflare
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}



      --------


      MYSQL_PASSWORD=examplepassword
MYSQL_ROOT_PASSWORD=examplepassword
MYSQL_USER=nextcloud
MYSQL_DATABASE=nextcl
