networks:
  cloudflare:
    external: true
  backend:
    external: true
services:
  cloudflaretunnel:
    container_name: cloudflaretunnel-homelab
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN} # Ensure TUNNEL_TOKEN is defined in an .env file or passed as an environment variable
    command: tunnel --no-autoupdate run 
    networks:
      - cloudflare
      - backend